import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Menu from "@/components/menu";
const montserratfont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose desired font weights
  variable: "--font-montserrat", // CSS variable for the font
});

export const metadata: Metadata = {
  title: "shop-maneger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratfont.variable} bg-gray-100 antialiased h-screen`}
      >
        <Toaster />
        <main>{children}</main>
        <Menu />
      </body>
    </html>
  );
}
