import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserratfont = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Choose desired font weights
  variable: "--font-montserrat", // CSS variable for the font
});

export const metadata: Metadata = {
  title: "shop-maneger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserratfont.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
